### ISSUE TITLE
👑[Enhancement] 设置图片cdn与图片格式

### ISSUE THREAD

**Issue by zhongfly** [misaka10843/copymanga-download#11]
### 🥰 需求描述(Description)

拷贝漫画app的api支持在请求头中设置相应参数控制图片cdn或图片格式

### 🧐 解决方案(Solution)

在headers中
region参数控制图片cdn地址，0指国外cdn，1指国内cdn
webp参数控制是否返回webp图片，0为否，返回jpeg格式，1为是。

### 🚑 其他信息(Other Information)

app的api（api.copymanga.net）不是应该headers模仿app的吗？怎么用的是浏览器的ua……
refer： https://github.com/zhongfly/tachiyomi-extensions/blob/copymangas/src/zh/copymangas/src/eu/kanade/tachiyomi/extension/zh/copymangas/CopyMangas.kt#L233

**Comment by misaka10843** [comment]
> 

关于API的UA，其实较早时候是直接F12抓出来api的www
所以就使用的浏览器的UA

然后就是cdn的话的确是不知道的qwq
关于自动选择cdn会提上日程的

然后就是webp的参数其实我认为没有什么用（反正都能下载就对了www）

**Comment by zhongfly** [comment]
> > 
> 
> 关于API的UA，其实较早时候是直接F12抓出来api的www 所以就使用的浏览器的UA
> 
> 然后就是cdn的话的确是不知道的qwq
> 
> 然后就是webp的参数其实我认为没有什么用（反正都能下载就对了www）

我已经做完了 #12

**Comment by zhongfly** [comment]
webp体积更小，占用空间更小
而且我怀疑你之前代码下载的其实都是webp格式，我记得api是默认返回webp的

**Comment by misaka10843** [comment]
> webp体积更小，占用空间更小 而且我怀疑你之前代码下载的其实都是webp格式，我记得api是默认返回webp的

的确api默认返回webp的🤣
（因为之前与一个做第三方copymanga网站的小伙伴交流过api，所以并没有了解这么深🤣）

**Comment by misaka10843** [comment]
感谢大佬的修改与建议🤣
我这几天会重新写一下manga_daownload🤣

**Comment by zhongfly** [comment]
cdn就如我提到的一样，其实作用类似于代理。
国内cdn是可以国内直连的，不需要代理
国外cdn需要代理，否则速度很慢
