### ISSUE TITLE
下载不了了，大佬能修复一下吗？

### ISSUE THREAD

**Issue by KILLER2017** [misaka10843/copymanga-download#3]

**Comment by misaka10843** [comment]
请问一下能否给下截图，或者错误输出日志qwq

**Comment by misaka10843** [comment]
已解决，问题是因为copymanga换域名了(copymanga.com->copymanga.net)
现在可以用了qwq
[windows下载](https://github.com/misaka10843/copymanga-download/actions/runs/1896208672)
[Linux下载](https://github.com/misaka10843/copymanga-download/actions/runs/1896208671)

**Comment by misaka10843** [comment]
如果还有其他类似问题可以重新开放此issue，感谢支持qwq
