### ISSUE TITLE
网站的开发者似乎又开了一个网站，基本相同，连接质量更好，涵盖内容多

### ISSUE THREAD

**Issue by longyiqiang** [misaka10843/copymanga-download#5]
希望能够添加api来支持网站中漫画部分的下载。
网站链接如下：
https://www.manga2022.com

**Comment by misaka10843** [comment]
虽然但是，这似乎是一个18+的网站吧🤣

**Comment by longyiqiang** [comment]
好的👌，这个的免费漫画板块中的内容和copymanga是一样的，可以只弄这个板块。感谢您的回答。

**Comment by misaka10843** [comment]
略微post了一下，原以为copymanga的站长应该不会两站同个api的请求方式，结果我错了www

现在就准备在程序启动时让用户选择想从哪个站点下应该就可以了qwq

（其实也就是替换了域名而已www）

**Comment by longyiqiang** [comment]
❤️

**Comment by misaka10843** [comment]
![图片](https://user-images.githubusercontent.com/69132853/155875399-2be3ea67-3a74-4744-a336-8bfb39c4fba2.png)
有一说一这API真怪，postman和python的re都获取不了，但是浏览器可获取，而且都设置了相同的UA

可能对此网站的支持会无效吧

**Comment by misaka10843** [comment]
因为无法知道此站章节API中的获取方式

此议题将暂停维护与开发（但是还是会努力试试的）

可能过一会会重新开放此议题，也有可能会关闭此议题

**Comment by misaka10843** [comment]
因为无法通过网络查询到对应api（不如说API直接是服务端渲染后再发客户端）

使用copymanga中的API也无法正常获取

所以此议题暂时关闭

感谢支持
