### ISSUE TITLE
[问题]填入tion后进入选择搜索；收藏的选项，选择任意一个都会瞬间退出

### ISSUE THREAD

**Issue by bearcloney** [misaka10843/copymanga-download#7]
您是想搜索还是查看您的收藏？(1:搜索，2:收藏  默认1

选择1 填入任意文字 后瞬间退出

选择2 直接退出

什么原因求解

**Comment by misaka10843** [comment]
选择2直接退出可能是因为token没有填好吧qwq
选择1理论来说是没有问题的www
最好还是说一下您是从**actions**下载的还是**releases**下载的比较好（比较两个并不是同步的www）

**Comment by misaka10843** [comment]
![图片](https://user-images.githubusercontent.com/69132853/157140066-9ac0e0e8-f158-4535-9d6a-ccab6a53bb8f.png)
![图片](https://user-images.githubusercontent.com/69132853/157140113-001f33c3-9f07-49f1-9ed4-2489001e23a0.png)
我在运行的时候似乎并没有此类问题，可能是您的版本过低造成的？

**Comment by misaka10843** [comment]
如果出现问题可以试试使用另一个分支的代码运行试试（但是您应该要先测试主分支的py文件再测试此分支）
分支：https://github.com/misaka10843/copymanga-download/tree/add_relamanga_and_proxy

**Comment by bearcloney** [comment]
谢谢大佬热心回复，问题已经圆满解决了(›´ω`‹ )
主要原因是我路由器挂着梯子，流量可能走了翻墙结果就不行了(；´д｀)
（当时actions和releases都下了没成功）现在用的是releases版的
ᕕ( ᐛ )ᕗ

**Comment by misaka10843** [comment]
那就好,我还以为测试分支的PR直接合并了www
